### ISSUE TITLE
IndexError causing game to crash

### ISSUE THREAD

**Issue by ngjunsiang** [PohAnson/ChessGame#13]
## Issue description

The game is unable to run beyond the first move. During the NEXT TURN phase, it crashes.

## Steps to reproduce the issue

1. Start the game (with debug=True)
2. Key in a valid move at the prompt

## Expected result

Game should update the board and continue

## Actual result

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/runner/ChessGame/main.py", line 14, in <module>
    game.next_turn()
  File "/home/runner/ChessGame/chess.py", line 584, in next_turn
    if self.checkmate(self.turn):
  File "/home/runner/ChessGame/chess.py", line 528, in checkmate
    if self.valid_move(coord, self.attacking_pieces[0][1]) and not self.check(colour):
IndexError: list index out of range
```
## Screenshot

![image](https://user-images.githubusercontent.com/45561895/87382124-ca83fc80-c5c8-11ea-94b3-9fbf279df4ed.png)

**Comment by ngjunsiang** [comment]
Use of `attacking_pieces` attribute relies on underlying implementation (attribute being a list) and makes debugging more difficult—have to trace where it was initialised and modified, and its value changes unpredictably.

Should use an abstract method, e.g. `get_kingthreat_coords()` to search for possible attacking pieces and return the list.

Related issue: #17
